R-DTH/Models/dealer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dealer()
        {
            this.dealer_order = new HashSet<dealer_order>();
        }

        public string LoginErrorMessage { get; set; }
        public int dealer_id { get; set; }
        public string dealer_name { get; set; }
        public Nullable<long> dealer_contact_no { get; set; }
        public string dealer_email { get; set; }
        public string dealer_password { get; set; }
        public string dealer_address { get; set; }
        public Nullable<long> dealer_totalypaid { get; set; }
        public Nullable<int> dealer_payment_left { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dealer_order> dealer_order { get; set; }
    }
}

R-DTH/Controllers/dealersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using R_DTH.Models;

namespace R_DTH.Controllers
{
    public class dealersController : Controller
    {
        private rdthEntities db = new rdthEntities();

        // GET: dealers
        public ActionResult Index()
        {
            return View(db.dealers.ToList());
        }

        public ActionResult Dealers()
        {
            return View(db.dealers.ToList());
        }
        // GET: dealers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dealer dealer = db.dealers.Find(id);
            if (dealer == null)
            {
                return HttpNotFound();
            }
            return View(dealer);
        }

        // GET: dealers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: dealers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "dealer_id,dealer_name,dealer_contact_no,dealer_email,dealer_password,dealer_address,dealer_totalypaid,dealer_payment_left")] dealer dealer)
        {
            if (ModelState.IsValid)
            {
                db.dealers.Add(dealer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dealer);
        }

        public ActionResult DealerLogin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DealerLogin([Bind(Include = "dealer_id,dealer_name,dealer_contact_no,dealer_email,dealer_password,dealer_address,dealer_totalypaid,dealer_payment_left")] dealer dealer)
        {
            if (ModelState.IsValid)
            {
                var user = db.dealers.FirstOrDefault(u => u.dealer_email == dealer.dealer_email && u.dealer_password == dealer.dealer_password);
                if (user != null)
                {
                    Session["DealerId"] = user.dealer_id.ToString();
                    Session["DealerName"] = user.dealer_name.ToString();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    dealer.LoginErrorMessage = "Invalid Username & Password!";
                    return View(dealer);
                }

            }

            return View();
        }


        public ActionResult logOut()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }


        // GET: dealers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dealer dealer = db.dealers.Find(id);
            if (dealer == null)
            {
                return HttpNotFound();
            }
            return View(dealer);
        }

        // POST: dealers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "dealer_id,dealer_name,dealer_contact_no,dealer_email,dealer_password,dealer_address,dealer_totalypaid,dealer_payment_left")] dealer dealer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dealer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dealer);
        }

        // GET: dealers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dealer dealer = db.dealers.Find(id);
            if (dealer == null)
            {
                return HttpNotFound();
            }
            return View(dealer);
        }

        // POST: dealers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dealer dealer = db.dealers.Find(id);
            db.dealers.Remove(dealer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

R-DTH/Controllers/faqsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using R_DTH.Models;

namespace R_DTH.Controllers
{
    public class faqsController : Controller
    {
        private rdthEntities db = new rdthEntities();

        // GET: faqs
        public ActionResult Index()
        {
            return View(db.faqs.ToList());
        }

        public ActionResult faq()
        {
            return View(db.faqs.ToList());
        }

        // GET: faqs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            faq faq = db.faqs.Find(id);
            if (faq == null)
            {
                return HttpNotFound();
            }
            return View(faq);
        }

        // GET: faqs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: faqs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "faq_id,faq_question,faq_answers")] faq faq)
        {
            if (ModelState.IsValid)
            {
                db.faqs.Add(faq);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(faq);
        }

        // GET: faqs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            faq faq = db.faqs.Find(id);
            if (faq == null)
            {
                return HttpNotFound();
            }
            return View(faq);
        }

        // POST: faqs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "faq_id,faq_question,faq_answers")] faq faq)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faq).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faq);
        }

        // GET: faqs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            faq faq = db.faqs.Find(id);
            if (faq == null)
            {
                return HttpNotFound();
            }
            return View(faq);
        }

        // POST: faqs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            faq faq = db.faqs.Find(id);
            db.faqs.Remove(faq);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

R-DTH/Views/dealers/Create.cshtml
@model R_DTH.Models.dealer

@{
    ViewBag.Title = "Create";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dealers
        <small>Admin View</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <br>
    <br>
    <div class="row">
        <!-- left column -->
        <div class="col-md-0">

        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <!-- general form elements disabled -->
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Register Dealer</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <div class="box-body form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.dealer_name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.dealer_name, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Contact #</label>

                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.dealer_contact_no, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.dealer_contact_no, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Email</label>

                                    <!-- textarea -->
                                    <div class="col-sm-10">
                                        <input type="email" name="dealer_email" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.dealer_email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Passwords</label>

                                    <!-- textarea -->
                                    <div class="col-sm-10">
                                        <input type="password" name="dealer_password" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.dealer_password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Address</label>

                                    <!-- textarea -->
                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.dealer_address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.dealer_address, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer ">
                                @Html.ActionLink("Back to List", "Index")   <input type="submit" value="Register" class="btn btn-info pull-right" />
                            </div>
                            <!-- /.box-footer -->
                        }
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

@*@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>dealer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.dealer_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dealer_contact_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_contact_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_contact_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dealer_email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dealer_password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dealer_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dealer_totalypaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_totalypaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_totalypaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dealer_payment_left, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dealer_payment_left, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dealer_payment_left, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

R-DTH/Views/dealers/DealerLogin.cshtml
@model R_DTH.Models.dealer

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Customer - Login</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>
    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link href="~/Content/Login/css/style.css" rel="stylesheet" />


</head>

<body>

    <!-- Form Mixin-->
    <!-- Input Mixin-->
    <!-- Button Mixin-->
    <!-- Pen Title-->
    <div class="pen-title">
        <h1>Dealer Login</h1>
        <span>R-DTH Service</span>
    </div>
    <!-- Form Module-->
    <div class="module form-module">
        <div class="toggle" style="visibility:hidden;">
        </div>
        <div class="form">
            <h2>Login to your account</h2>
            @using (Html.BeginForm(FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <input type="text" placeholder="Username" name="dealer_email" />
                <input type="password" placeholder="Password" name="dealer_password" />
                <button type="submit">Login</button>
            }
        </div>
        <div class="cta"><a href="http://andytran.me">@Html.DisplayFor(model => model.LoginErrorMessage)</a></div>
    </div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://codepen.io/andytran/pen/vLmRVp.js'></script>

    <script src="~/Content/Login/js/index.js"></script>
</body>
</html>

R-DTH/Views/dealers/Dealers.cshtml
@model IEnumerable<R_DTH.Models.dealer>

@{
    ViewBag.Title = "Dealers";
    Layout = "~/Views/Shared/_ThemeLayout.cshtml";
}

 <!-- banner -->
<div class="w3ls-banner contact-agileinfo">
    <div class="container">
        <h2 class="w3ls-title">Need help?</h2>
        <h3 class="w3-subtitle">We're here for you!</h3>
    </div>
</div>
<!-- //banner -->
<!-- breadcrumbs -->
<div class="w3layouts-breadcrumbs text-center">
    <div class="container">
        <span class="agile-breadcrumbs"><a href="@Url.Action("Index","Home")">Home</a> > <a href="@Url.Action("Dealers","Home")">Customer Care</a> > <span>Dealers</span></span>
    </div>
</div>
<!-- //breadcrumbs -->
<!-- //banner -->
<div class="w3l-main-contact">
    <div class="container">
        <div class="col-md-3 w3_agileits-contact-inner">
            <ul class="w3-inner-contact">
                <li class="active"><a href="@Url.Action("Dealers","dealers")">dealers</a></li>
                <li><a href="@Url.Action("Contact","Home")">contact us</a></li>
                <li><a href="@Url.Action("Faq","faqs")">faq</a></li>
            </ul>
        </div>
        <div class="col-md-9 agileinfo-contact-main-address">
            <div class="clearfix"></div>
            <div class="agileinfo-contact-main-address">
                <h6>R-DTH Digital TV  service providers</h6>
                @foreach (var item in Model)
                {
                    String abc = "name" + item.dealer_id;
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="@Html.DisplayName(abc+"a")">
                            <h5 class="panel-title asd">
                                <a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#@Html.DisplayName(abc)" aria-expanded="false"
                                   aria-controls="@Html.DisplayName(abc)">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><i class="glyphicon glyphicon-chevron-down" aria-hidden="true"></i>Dealer Near You
                                </a>
                            </h5>
                        </div>
                        <div id="@Html.DisplayName(abc)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false"
                             style="height: 0px;">
                            <div class="panel-body panel_text">
                                <div class="w3three-contact-left">
                                    <div class="address">
                                        <h5>Address:</h5>
                                        <p><i class="glyphicon glyphicon-home"></i> @Html.DisplayFor(modelItem => item.dealer_address)
 </p>
                                    </div>
                                    <div class="address address-mdl">
                                        <h5>Phone:</h5>
                                        <p><i class="glyphicon glyphicon-earphone"></i> +9900887766</p>
                                        <p><i class="glyphicon glyphicon-phone"></i> @Html.DisplayFor(modelItem => item.dealer_contact_no)
</p>
                                    </div>
                                    <div class="address">
                                        <h5>Email:</h5>
                                        <p><i class="glyphicon glyphicon-envelope"></i> <a href="mailto:info@example.com">@Html.DisplayFor(modelItem => item.dealer_email)</a></p>
                                    </div>
                                </div>
                                <img src="images/c3.png" class="img-responsive" alt="" />
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                }
                    @*<div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingThree">
                            <h5 class="panel-title asd">
                                <a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false"
                                   aria-controls="collapseThree">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><i class="w3ls-icon glyphicon glyphicon-chevron-down" aria-hidden="true"></i>Dealer Near You
                                </a>
                            </h5>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree" aria-expanded="false"
                             style="height: 0px;">
                            <div class="panel-body panel_text">
                                <div class="w3three-contact-left">
                                    <div class="address">
                                        <h5>Address:</h5>
                                        <p><i class="glyphicon glyphicon-home"></i> 333 Broome St New York, NY 10002, </p>
                                    </div>
                                    <div class="address address-mdl">
                                        <h5>Phone:</h5>
                                        <p><i class="glyphicon glyphicon-earphone"></i> +9900887766</p>
                                        <p><i class="glyphicon glyphicon-phone"></i> +11 222 333</p>
                                    </div>
                                    <div class="address">
                                        <h5>Email:</h5>
                                        <p><i class="glyphicon glyphicon-envelope"></i> <a href="mailto:info@example.com">mail@example.com</a></p>
                                    </div>
                                </div>
                                <img src="images/c3.png" class="img-responsive" alt="" />
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingFour">
                            <h5 class="panel-title asd">
                                <a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false"
                                   aria-controls="collapseFour">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><i class="glyphicon glyphicon-chevron-down" aria-hidden="true"></i>Dealer Near You
                                </a>
                            </h5>
                        </div>
                        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour" aria-expanded="false"
                             style="height: 0px;">
                            <div class="panel-body panel_text">
                                <div class="w3three-contact-left">
                                    <div class="address">
                                        <h5>Address:</h5>
                                        <p><i class="glyphicon glyphicon-home"></i> 333 Broome St New York, NY 10002, </p>
                                    </div>
                                    <div class="address address-mdl">
                                        <h5>Phone:</h5>
                                        <p><i class="glyphicon glyphicon-earphone"></i> +9900887766</p>
                                        <p><i class="glyphicon glyphicon-phone"></i> +11 222 333</p>
                                    </div>
                                    <div class="address">
                                        <h5>Email:</h5>
                                        <p><i class="glyphicon glyphicon-envelope"></i> <a href="mailto:info@example.com">mail@example.com</a></p>
                                    </div>
                                </div>
                                <img src="images/c3.png" class="img-responsive" alt="" />
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>*@
                
                </div>
            </div>
        </div>
    </div>
</div>

R-DTH/Views/dealers/Delete.cshtml
@model R_DTH.Models.dealer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>dealer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dealer_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dealer_contact_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_contact_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dealer_email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dealer_password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dealer_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dealer_totalypaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_totalypaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dealer_payment_left)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dealer_payment_left)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>