R-DTH/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.customer_order = new HashSet<customer_order>();
            this.dealer_order = new HashSet<dealer_order>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_details { get; set; }
        public string product_img { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<int> product_charges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_order> customer_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dealer_order> dealer_order { get; set; }
    }
}

R-DTH/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using R_DTH.Models;
using System.IO;
using System.Web.UI.WebControls;

namespace R_DTH.Controllers
{
    public class productsController : Controller
    {
        private rdthEntities db = new rdthEntities();

        // GET: products
        public ActionResult Index()
        {
            return View(db.products.ToList());
        }

        public ActionResult Products()
        {
            return View(db.products.ToList());
        }

        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,product_name,product_details,ImageFile,product_charges")] product product)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileName(product.ImageFile.FileName);
                product.product_img = fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/AdminStuff/dist/img/"), fileName);
                product.ImageFile.SaveAs(fileName);
                db.products.Add(product);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,product_name,product_details,product_img,ImageFile,product_charges")] product product)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileName(product.ImageFile.FileName);
                product.product_img = fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/AdminStuff/dist/img/"), fileName);
                product.ImageFile.SaveAs(fileName);
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

R-DTH/Views/products/Create.cshtml
@model R_DTH.Models.product

@{
    ViewBag.Title = "Product";
}

<section class="content-header">
    <h1>
        Product
        <small>Admin View</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Product</a></li>
        <li><a href="#">List</a></li>
        <li class="active">Add</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <br>
    <br>
    <div class="row">
        <!-- left column -->
        <div class="col-md-0">

        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <!-- general form elements disabled -->
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Add New Product</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8">

                        @using (Html.BeginForm("Create","products", FormMethod.Post,new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="box-body form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Image</label>

                                    <div class="col-sm-10">
                                        @*@Html.EditorFor(model => model.product_img, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_img, "", new { @class = "text-danger" })*@
                                        <input type="file" name="ImageFile" class="form-control " />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Charges</label>

                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.product_charges, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_charges, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Details</label>

                                    <!-- textarea -->
                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.product_details, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_details, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer ">
                                @Html.ActionLink("Back to List", "Index")   <input type="submit" value="Add Now" class="btn btn-info pull-right" />
                            </div>
                            <!-- /.box-footer -->
                        }
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

@*@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_charges, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_charges, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_charges, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

R-DTH/Views/products/Delete.cshtml
@model R_DTH.Models.product

@{
    ViewBag.Title = "Delete";
}


<section class="content-header">
    <h1>
        <small>Admin View</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Package</a></li>
        <li><a href="#">List</a></li>
        <li class="active">Delete</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <br>
    <br>
    <div class="row">
        <!-- left column -->
        <div class="col-md-0">

        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <!-- general form elements disabled -->
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Delete Prouduct</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8">
                        <h3>Are you sure you want to delete this?</h3>
                        <div>
                            <h4>product</h4>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.product_name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.product_name)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.product_details)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.product_details)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.product_img)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.product_img)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.product_charges)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.product_charges)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-default" /> |
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            }
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

R-DTH/Views/products/Details.cshtml
@model R_DTH.Models.product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_charges)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_charges)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

R-DTH/Views/products/Edit.cshtml
@model R_DTH.Models.product

@{
    ViewBag.Title = "Edit";
}

<section class="content-header">
    <h1>
        Edit Form
        <small>Admin View</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Product</a></li>
        <li><a href="#">List</a></li>
        <li class="active">Edit</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <br>
    <br>
    <div class="row">
        <!-- left column -->
        <div class="col-md-0">

        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <!-- general form elements disabled -->
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Products</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8">

                        @using (Html.BeginForm("Edit", "products", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="box-body form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.product_id)
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Image</label>

                                    <div class="col-sm-10">
                                        @*@Html.EditorFor(model => model.product_img, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_img, "", new { @class = "text-danger" })*@
                                        <input type="file" name="ImageFile" class="form-control " />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Charges</label>

                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.product_charges, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_charges, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-2 control-label">Details</label>

                                    <!-- textarea -->
                                    <div class="col-sm-10">
                                        @Html.EditorFor(model => model.product_details, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.product_details, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer ">
                                @Html.ActionLink("Back to List", "Index")   <input type="submit" value="Update" class="btn btn-info pull-right" />
                            </div>
                            <!-- /.box-footer -->
                        }
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.product_id)

        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_charges, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_charges, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_charges, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

R-DTH/Views/products/Index.cshtml
@model IEnumerable<R_DTH.Models.product>

@{
    ViewBag.Title = "Products";
}

<section class="content-header">
    <h1>
        Product List
        <small>Admin View</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Product</a></li>
        <li><a href="#">List</a></li>
        <li class="active">View</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        @Html.ActionLink("Add New Product", "Create")

                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Product Name</th>
                                <th>Product Image</th>
                                <th>Product Charges</th>
                                <th>Product Details</th>
                                <th>Take Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.product_name)
                                    </td>
                                    <td align="center">
                                       <img style="width:70px; height:50px;" src="~/Content/AdminStuff/dist/img/@Html.DisplayFor(modelItem => item.product_img)" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.product_charges)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.product_details)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.product_id }) |
                                        @*@Html.ActionLink("Details", "Details", new { id = item.product_id }) |*@
                                        @Html.ActionLink("Delete", "Delete", new { id = item.product_id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Product Name</th>
                                <th>Product Image</th>
                                <th>Product Charges</th>
                                <th>Product Details</th>
                                <th>Take Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.product_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.product_details)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.product_img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.product_charges)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.product_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.product_details)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.product_img)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.product_charges)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.product_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.product_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.product_id })
        </td>
    </tr>
}

</table>*@